jdbc:
  driverName: "com.mysql.jdbc.Driver"
  URL: "jdbc:mysql://localhost:3306/component_data_jdbc?allowPublicKeyRetrieval=true&useSSL=false"
  username: "attila"
  password: "password"
  poolSize: 5